title: MMDM
subtitle: Learn by doing
url: "" # the base url and protocol e.g https://blog.masteringmdm.com
baseurl: "" # subpath of your site, e.g /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog

collections:
  authors:
   output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# pagination of posts
paginate: 5
per_page: 4
paginate_path: "/blog/page/:num/"

# Build settings
plugins:
  - jekyll-paginate

