title: NOOTORIOUS
subtitle:
url: ""# the base url and protocol e.g https://blog.masteringmdm.com
baseurl: "" # subpath of your site, e.g /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: About
      url: /about

# syntax
permalink: pretty

collections:
  authors:
   output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      thumbnail: /assets/img/posts/thumbnail.png
  - scope:
      path: ""
    values:
      layout: "default"

# pagination of posts
paginate: 5
paginate_path: "/blog/page/:num"

# Build settings
plugins:
  - jekyll-paginate

